### ISSUE TITLE
[Getting Started with Sass] Failed to install

### ISSUE THREAD

**Issue by gusdecool** [foundation/foundation-emails#1051]
Failed to install the foundation, tested with

````shell
% node --version
v15.11.0

% npm --version
7.6.0
````

**How can we reproduce this bug?**

Followed the instruction in https://get.foundation/emails/docs/sass-guide.html

```shell
npm install --global foundation-cli
foundation new --framework emails

// got output
fs.js:51
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:51:5
    at req_ (/usr/local/lib/node_modules/foundation-cli/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/usr/local/lib/node_modules/foundation-cli/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/foundation-cli/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
```

**What did you expect to happen?**

Should success install Foundation for new project

**What happened instead?**

Got error when tried install command
```shell
// got output
fs.js:51
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:51:5
    at req_ (/usr/local/lib/node_modules/foundation-cli/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/usr/local/lib/node_modules/foundation-cli/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/foundation-cli/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
```

**What email clients does this happen in?**

none, it failed on installation.

**Comment by DanielRuf** [comment]
Please see https://github.com/foundation/foundation-emails/issues?q=is%3Aissue+sort%3Aupdated-desc+primordials+is%3Aclosed

So you should try to switch to Node 10 using nodenv, n, or nvm.

**Comment by gusdecool** [comment]
Thanks @DanielRuf, Node v10 already in maintenance phase and will end in April 2021. I don't think we will want to use outdated Node version. But still, thanks for the support.

**Comment by DanielRuf** [comment]
> Thanks @DanielRuf, Node v10 already in maintenance phase and will end in April 2021.

I'm aware of this. Unfortunately we did not have time to upgrade the dependencies and I'm not much involved in Foundation anymore. Technically it should not be a problem, because you use the Node version only for the development and build script.
