### ISSUE TITLE
[Getting Started with Sass] command not found: foundation

### ISSUE THREAD

**Issue by tasteitslight** [foundation/foundation-emails#1094]
Hi All,

I'm getting started with Foundation using the [SASS Guide](https://get.foundation/emails/docs/sass-guide.html). 

Running:
`foundation new --framework emails`
Returns the following error:
`zsh: command not found: foundation`

I've troubleshooted extensively, even uninstalled npm using homebrew and reinstalled. This is my path:

```
export PATH=${PATH}:/usr/local/mysql/bin/
export PATH="/usr/local/bin:$PATH"
export PATH=/Users/sunyata/.npm-global/lib/node_modules:$PATH
#export PATH="$PATH:~/.composer/vendor/bin"

```

I added the third line because that seems to be where the foundation pack is installed. 

Thanks in advance for your help.
Will

**Comment by solverware** [comment]
I'm also getting an error on running that command:

C:\Users\solve\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\string-kit\lib\format.js:327
                markupTarget = this.shiftedMarkup?.[ runtime.shift ]?.[ markup ] ;
                                                  ^

SyntaxError: Unexpected token .
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

**Comment by Geddo** [comment]
Having the same error. Went back to node 10.18.0 and  foundation-cli@2.2.6:
n 10.18.0
npm install --global foundation-cli@2.2.6
