### ISSUE TITLE
Feature request - Support latest nodeJS versions

### ISSUE THREAD

**Issue by ItamarGronich** [foundation/foundation-emails#1113]
### Desired behavior

Foundation runs on latest node versions (16, 17)

### Current behavior

Foundation runs on node version no greater than 10.

### This raised a question
Why does the docs say that foundation doesn't support node > 10? Version 2.4.0 now uses dart sass instead of node-sass so there should be less tight coupling with a specific node version. The only thing i can think of that might be the `xmlbuilder` package used by `gulp-litmus` because it specifies an engine field not compatible.
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/14963977/163806407-e265a24a-3ba8-492c-8242-4e32a479eb7b.png">

**Comment by justingit** [comment]
This issue is leaving Foundation for Emails dead in the water. I have to drag an old limping laptop out whenever I need to build something.

**Comment by ItamarGronich** [comment]
Yes, this makes foundation unusable in the new apple silicon macbooks.

**Comment by tnog** [comment]
To get around this for the time being you can use NVM to install and use different versions of node as needed: https://github.com/nvm-sh/nvm 

On Mac OS see: https://dev-yakuza.posstree.com/en/environment/nvm/ for install and configuration using Homebrew

**Comment by justingit** [comment]
Can anyone confirm v10 can be installed using nvm on an M1 mac? Fails for me at least.

**Comment by tnog** [comment]
<img width="385" alt="Screen Shot 2022-04-25 at 2 27 20 PM" src="https://user-images.githubusercontent.com/2049299/165177925-38ef7ba9-e9cb-43f3-b9b1-05536b5f225b.png">

**Comment by justingit** [comment]
Appreciate the check, @tnog.  Must be an issue in my environment.  I will investigate further. 

```
justin@m1 ~ % nvm install 10.24.1 

# build verbosity and other errors, including, 

../deps/openssl/config/archs/linux-x86_64/asm_avx2/crypto/aes/aesni-x86_64.s:4474:8: error: invalid alignment value
.align 64
       ^
make[1]: *** [/Users/justin/.nvm/.cache/src/node-v10.24.1/files/out/Release/obj.target/openssl/deps/openssl/config/archs/linux-x86_64/asm_avx2/crypto/aes/aesni-x86_64.o] Error 1
rm c0b1278d8e592e490c896cac3f2c38b439c8a5d3.intermediate
make: *** [node] Error 2
nvm: install v10.24.1 failed!
justin@m1 ~ % 

```

**Comment by ItamarGronich** [comment]
> To get around this for the time being you can use NVM to install and use different versions of node as needed: [nvm-sh/nvm](https://github.com/nvm-sh/nvm)
> 
> On Mac OS see: [dev-yakuza.posstree.com/en/environment/nvm](https://dev-yakuza.posstree.com/en/environment/nvm/) for install and configuration using Homebrew

@tnog This is a feature request for upgrading foundation to work on the latest node versions.
It's not a bug - I have no actual problem with running foundation as i'm already using NVM to set node to the required version for foundation.

However, I would like to upgrade node to the latest release since the older 10.x versions are now end of life and no longer maintained.
So, if foundation is to be a product used in production it has to upgrade to maintain the necessary level of security.

Also, to make node < 16 work on m1 macs you have to use rosetta otherwise only node >= 16 works natively on m1 since it was the first release to compile to darwin-arm64 target. node < 16 only compiled to darwin-64 (intel chips).

**Comment by tnog** [comment]
@ItamarGronich that's clearly understood. Was responding to users like @justingit who weren't aware of workaround.

**Comment by tataue** [comment]
> Can anyone confirm v10 can be installed using nvm on an M1 mac? Fails for me at least.

not okay. tested.

**Comment by boreyko1** [comment]
> Can anyone confirm v10 can be installed using nvm on an M1 mac? Fails for me at least.

Works fine using https://github.com/tj/n and node@10.24.1

**Comment by justingit** [comment]
n looks promising, I'm still having problems with the openssl dep, 

```
../deps/openssl/config/archs/linux-x86_64/asm_avx2/crypto/aes/aesni-mb-x86_64.s:6:1: error: unknown directive
.type aesni_multi_cbc_encrypt,@function

```

**Comment by ItamarGronich** [comment]
I'm sorry for being that guy but this discussion is off topic.
Wether node 10 can or can not be installed on M1 macs is off topic.

This is a feature request for foundation to upgrade to latest node versions.

**Comment by wegnertm** [comment]
Can we please get something on the requirements/installation instructions! I just wasted hours trying to get my emails to compile not knowing I shouldn't have updated my node version. Extremely frustrating.

**Comment by viking1304** [comment]
> Can we please get something on the requirements/installation instructions! I just wasted hours trying to get my emails to compile not knowing I shouldn't have updated my node version. Extremely frustrating.

EDIT: The instructions on the web page https://get.foundation/emails/docs/sass-guide.html are not good and should be ignored, so I removed my original answer.

I just wrote a proper answer in another thread (with updated information that I didn't have when I wrote my previous answer):
https://github.com/foundation/foundation-emails/issues/1129#issuecomment-1314059792

**Comment by paulbcurious** [comment]
Adding a small piece of information here regarding the NVM work-around. I thought just running `nvm use 10` would give me the node version I needed, but it loads node 10.24. But if I specify `nvm use 10.23.3` it shifts the version of NPM and I am able to run and build the emails. Maybe this helps some of you that were in my position looking for that work-around. Of course supporting the latest node would be ideal...

````
npm does not support Node.js v10.24.1
You should probably upgrade to a newer version of node as we
can't make any promises that npm will work with this version.
You can find the latest version at https://nodejs.org/
/Users/paulbanagas/.nvm/versions/node/v10.24.1/lib/node_modules/npm/lib/npm.js:32
  #unloaded = false
  ^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at module.exports (/Users/paulbanagas/.nvm/versions/node/v10.24.1/lib/node_modules/npm/lib/cli.js:22:15)
    at Object.<anonymous> (/Users/paulbanagas/.nvm/versions/node/v10.24.1/lib/node_modules/npm/bin/npm-cli.js:2:25)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
paulbanagas@Pauls-MacBook-Pro PBD_Ebl % nvm use 10.23.3
Now using node v10.23.3 (npm v6.14.11)

paulbanagas@Pauls-MacBook-Pro PBD_Ebl % npm run start

> foundation-emails@2.4.0 start /Users/paulbanagas/Desktop/PBDcode/PBD_Ebl
> gulp

[11:04:23] Using gulpfile ~/Desktop/PBDcode/PBD_Ebl/gulpfile.js
[11:04:23] Starting 'default'...
```
`

**Comment by joeworkman** [comment]
Closing as part of a project-wide issue triage. This issue relates to outdated Node.js / Sass / Gulp version requirements.

The project is being modernized with updated tooling and dependency requirements. If you're still experiencing build issues after the next release, please open a new issue with your environment details. Thanks!
