### ISSUE TITLE
Can't build email project. What versions of node should I use? What SASS should I be using? 

### ISSUE THREAD

**Issue by wegnertm** [foundation/foundation-emails#1129]
I'm trying to get my emails to compile and currently running into an issue on `npm run build` command. I wanted to search the Get Help link on https://get.foundation/emails/docs/sass-guide.html but it takes me to a "site can't be reached" page: https://foundation.discourse.group/ - can this get fixed or can someone help me with my current issue: 

![image](https://user-images.githubusercontent.com/40865491/199116365-af230ba4-f607-476c-ae48-b4a1d20a8ebd.png)

**Comment by davehoran** [comment]
I would suggest emailing Zurb to see if there is a new discussion forum for
the product. They may have changed the platform they use for support.

On the SASS error, is there anything in the SASS file that could be causing
the error? Can you validate the SASS with another tool?

**Comment by wegnertm** [comment]
Ok I'll see if I can locate their email. Seems like they don't really keep the site up to date with which versions don't work. 

I'm not sure what you mean by validating the SASS? I ran `sass --version` and this is what shows up: 
![image](https://user-images.githubusercontent.com/40865491/199118872-52e2f4c1-6315-4de1-aed3-c264e8ca3eba.png)

**Comment by wegnertm** [comment]
Could someone provide me with what version of node, npm, and foundation-cli they're using that's working?

**Comment by glynszasz** [comment]
> Could someone provide me with what version of node, npm, and foundation-cli they're using that's working?

My current working setup has the following versions. Yarn is used for compiling
npm: 6.14.15
node: 14.18.3
foundation: 2.3.2
Yarn: 1.22.19
OS: Mac OS Big Sur 11.7

All is run through VS Code 1.7.2

Hope this helps.

**Comment by wegnertm** [comment]
> > Could someone provide me with what version of node, npm, and foundation-cli they're using that's working?
> 
> My current working setup has the following versions. Yarn is used for compiling npm: 6.14.15 node: 14.18.3 foundation: 2.3.2 Yarn: 1.22.19 OS: Mac OS Big Sur 11.7
> 
> All is run through VS Code 1.7.2
> 
> Hope this helps.

Thank you I'll give it a try, I'm running on Windows 10 so we will see if it makes any difference.

**Comment by danigirl329** [comment]
FYI upon a fresh install i needed to modify the gulpfile.js to require 'sass' :
`var sass = require('gulp-sass')(require('sass'));`

```
npm -v: 8.3.1
node -v: v18.12.0
yarn -v: 1.22.19
macOS Monterey: 12.6
```

**Comment by viking1304** [comment]
> I'm trying to get my emails to compile and currently running into an issue on `npm run build` command. I wanted to search the Get Help link on https://get.foundation/emails/docs/sass-guide.html but it takes me to a "site can't be reached" page: https://foundation.discourse.group/ - can this get fixed or can someone help me with my current issue:

The instructions on the web page https://get.foundation/emails/docs/sass-guide.html are not good. I just discovered that [foundation-cli](https://github.com/foundation/foundation-cli) is now an archived project, so it should not be used.

Instructions on this GitHub page are fine:
https://github.com/foundation/foundation-emails#getting-started

Just note that you can use v14.21.1 without any problem.

**Comment by jeffsydor** [comment]
I'm having a similar issue with installing and running foundations emails on my M1 Mac.

npm -v: 9.1.3
node -v: 14.21.1
yarn -v: 1.22.19
MacOS: 12.6

I've followed all of the instructions above and STILL can't get this to set up properly. Here's the main error I'm getting when I do an npm start:

```
ConfigError: Multiple configuration files found. Please remove one:
 - package.json
 - /Users/<user>/Desktop/email projects/project/.babelrc
```

The contents of the package.json file:
```
{
  "name": "foundation-emails-template",
  "version": "2.4.0",
  "description": "Basic template for a Foundation for Emails project.",
  "repository": "foundation/foundation-emails-template",
  "main": "gulpfile.babel.js",
  "scripts": {
    "start": "gulp",
    "build": "gulp --production",
    "zip": "gulp zip --production",
    "litmus": "gulp litmus --production",
    "mail": "gulp mail --production"
  },
  "author": "Foundation <contact@get.foundation> (https://get.foundation)",
  "license": "MIT",
  "dependencies": {
    "foundation-emails": "^2.4.0"
  },
  "devDependencies": {
    "babel-core": "^6.3.26",
    "babel-preset-es2015": "^6.3.13",
    "babel-register": "^6.7.2",
    "beepbeep": "^1.2.0",
    "browser-sync": "^2.11.0",
    "colors": "^1.1.2",
    "gulp": "^4.0.2",
    "gulp-autoprefixer": "^7.0.1",
    "gulp-cached": "^1.1.0",
    "gulp-concat": "^2.6.0",
    "gulp-htmlmin": "^5.0.1",
    "gulp-if": "^3.0.0",
    "gulp-inject-string": "^1.1.0",
    "gulp-inline-css": "^3.4.0",
    "gulp-load-plugins": "^2.0.1",
    "gulp-postcss": "^8.0.0",
    "gulp-prettify": "^0.5.0",
    "gulp-prompt": "^1.2.0",
    "gulp-rename": "^1.2.2",
    "gulp-rsync": "0.0.8",
    "gulp-sass": "^4.1.0",
    "gulp-sass-lint": "^1.4.0",
    "gulp-sourcemaps": "^2.6.5",
    "gulp-uncss": "^1.0.1",
    "gulp-wrap": "^0.15.0",
    "gulp-zip": "^5.0.1",
    "gulp-awspublish": "^3.0.1",
    "gulp-cli": "^1.1.0",
    "gulp-html-src": "^1.0.0",
    "gulp-imagemin": "^2.4.0",
    "gulp-litmus": "0.0.7",
    "gulp-mail": "^0.1.1",
    "gulp-replace": "^0.5.4",
    "inky": "^1.4.1",
    "lazypipe": "^1.0.1",
    "merge-stream": "^1.0.0",
    "panini": "^1.3.0",
    "rimraf": "^2.3.3",
    "sass": "^1.35.2",
    "siphon-media-query": "^1.0.0",
    "yargs": "^4.1.0"
  },
  "babel": {
    "presets": [
      "es2015"
    ]
  }
}
```

The contents of the .babelrc file:
```
{
  "presets": ["es2015"]
}
```

Outside of this, I've been getting nothing but errors when trying to get this going. I would appreciate any help here. I have been losing weeks of time trying to get this up and running. 

thank you very much!

**Comment by PaulBDesignInc** [comment]
Adding a small piece of information here regarding the NVM work-around. I thought just running `nvm use 10` would give me the node version I needed, but it loads node 10.24. But if I specify `nvm use 10.23.3` it shifts the version of NPM and I am able to run and build the emails. Maybe this helps some of you that were in my position looking for that work-around. Of course supporting the latest node would be ideal...

````
npm does not support Node.js v10.24.1
You should probably upgrade to a newer version of node as we
can't make any promises that npm will work with this version.
You can find the latest version at https://nodejs.org/
/Users/paulbanagas/.nvm/versions/node/v10.24.1/lib/node_modules/npm/lib/npm.js:32
  #unloaded = false
  ^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at module.exports (/Users/paulbanagas/.nvm/versions/node/v10.24.1/lib/node_modules/npm/lib/cli.js:22:15)
    at Object.<anonymous> (/Users/paulbanagas/.nvm/versions/node/v10.24.1/lib/node_modules/npm/bin/npm-cli.js:2:25)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
paulbanagas@Pauls-MacBook-Pro PBD_Ebl % nvm use 10.23.3
Now using node v10.23.3 (npm v6.14.11)

paulbanagas@Pauls-MacBook-Pro PBD_Ebl % npm run start

> foundation-emails@2.4.0 start /Users/paulbanagas/Desktop/PBDcode/PBD_Ebl
> gulp

[11:04:23] Using gulpfile ~/Desktop/PBDcode/PBD_Ebl/gulpfile.js
[11:04:23] Starting 'default'...
```
`

**Comment by joeworkman** [comment]
Closing as part of a project-wide issue triage. This issue relates to outdated Node.js / Sass / Gulp version requirements.

The project is being modernized with updated tooling and dependency requirements. If you're still experiencing build issues after the next release, please open a new issue with your environment details. Thanks!
