### ISSUE TITLE
Special characters and nested html tags

### ISSUE THREAD

**Issue by gakimball** [foundation/foundation-emails#176]
_From @nwerr on February 22, 2016 16:15_

Using special characters with other html tags (span, br, a) inside a component results in an error.

Example:

```
<container>
    <row>
        <columns small="12" large="12">
            <p>äüö<span class="test">äüö</span>äüö</p>
        </columns>
    </row>
</container>
```

Error:

```
[17:13:04] Starting 'pages'...
[17:13:05] 'pages' errored after 271 ms
[17:13:05] SyntaxError: Unmatched selector: &#xE4;&#xFC;&#xF6;<a>&#xE4;&#xFC;&#xF6;</a>&#xE4;&#xFC;&#xF6;
    at parse (/home/niklas/webs/foundation/node_modules/inky/node_modules/css-what/index.js:85:9)
    at compileUnsafe (/home/niklas/webs/foundation/node_modules/inky/node_modules/css-select/lib/compile.js:31:14)
    at select (/home/niklas/webs/foundation/node_modules/inky/node_modules/css-select/index.js:18:49)
    at CSSselect (/home/niklas/webs/foundation/node_modules/inky/node_modules/css-select/index.js:41:9)
    at [object Object].exports.find (/home/niklas/webs/foundation/node_modules/inky/node_modules/cheerio/lib/api/traversing.js:34:21)
    at [object Object].module.exports (/home/niklas/webs/foundation/node_modules/inky/node_modules/cheerio/lib/cheerio.js:81:18)
    at new initialize (/home/niklas/webs/foundation/node_modules/inky/node_modules/cheerio/lib/static.js:26:20)
    at initialize (/home/niklas/webs/foundation/node_modules/inky/node_modules/cheerio/lib/static.js:23:14)
    at Inky.findNestedComponents (/home/niklas/webs/foundation/node_modules/inky/lib/inky.js:74:16)
    at Inky.<anonymous> (/home/niklas/webs/foundation/node_modules/inky/lib/inky.js:84:55)
```

_Copied from original issue: zurb/foundation-emails#45_

**Comment by gakimball** [comment]
Fixed in the latest version of Inky.
