### ISSUE TITLE
Undefined variable: "$container-background-color

### ISSUE THREAD

**Issue by mbesto** [foundation/foundation-emails#273]
When I `npm start` in a completely new build I get this error message:

```
[09:40:19] Finished 'pages' after 266 ms
[09:40:19] Starting 'sass'...
Error in plugin 'sass'
Message:
    node_modules/foundation-emails/scss/grid/_grid.scss
Error: Undefined variable: "$container-background-color".
        on line 31 of node_modules/foundation-emails/scss/grid/_grid.scss
>>     background: $container-background-color;
   ----------------^
[09:40:19] Error: ENOENT: no such file or directory, open 'dist/css/app.css'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at inliner (gulpfile.babel.js:93:16)
    at inline (gulpfile.babel.js:71:28)
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at asyncRunner (/Users/mikebestvina/Code/zurb/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/async-done/index.js:36:18)
    at _combinedTickCallback (node.js:370:9)
    at process._tickDomainCallback (node.js:425:11)
[09:40:19] 'build' errored after 687 ms
[09:40:19] 'default' errored after 688 ms
```

Really simple fix here. On this line https://github.com/zurb/foundation-emails/blob/develop/scss/settings/_settings.scss#L34 change `$container-background: $white;` to `$container-background-color: $white;`

Then `npm start` works properly.

**Comment by mbesto** [comment]
This appears to be already fixed. When I do `foundation new --framework emails` in the cli it installs:

```
inky@1.3.3 node_modules/inky
├── object-values@1.0.0
├── multiline@1.0.2 (strip-indent@1.0.1)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── through2@2.0.1 (xtend@4.0.1, readable-stream@2.0.6)
├── foundation-emails@2.0.0
├── vinyl-fs@2.4.2 (merge-stream@1.0.0, is-valid-glob@0.3.0, vali-date@1.0.0, object-assign@4.0.1, graceful-fs@4.1.3, lazystream@1.0.0, strip-bom-stream@1.0.0, strip-bom@2.0.0, lodash.isequal@4.1.1, through2-filter@2.0.0, vinyl@1.1.1, readable-stream@2.0.6, duplexify@3.4.3, glob-stream@5.3.2)
└── cheerio@0.20.0 (entities@1.1.1, dom-serializer@0.1.0, css-select@1.2.0, htmlparser2@3.8.3, jsdom@7.2.2, lodash@4.6.1)
```

Of which this is fixed in v2.0.0 of foundation-emails repo: https://github.com/zurb/foundation-emails/blob/v2.0.0/scss/grid/_grid.scss

Any ideas?

**Comment by pdnellius** [comment]
@mbesto I can also confirm this issue and have fixed it in the same way.

**Comment by tdhartwick** [comment]
Looks like this has been resolved. Let us know if you're still seeing this issue!
