### ISSUE TITLE
Npm start fails to run.

### ISSUE THREAD

**Issue by Hectorhammett** [foundation/foundation-emails#480]
I've seen this error been post but i haven't been able to find a solution. The first time i tried to make run Inky was a problem, and i thought this time would be easier but apparently it's not the case.

I installed from npm install foundation-cli and created a project, then i run
`npm start`

and it's giving me the folowing error:

> foundation-emails-template@1.0.0 start /var/www/html/emails
> gulp

[11:41:29] Failed to load external module babel-register
[11:41:29] Requiring external module babel-core/register
[11:41:32] Using gulpfile /var/www/html/emails/gulpfile.babel.js
[11:41:32] Starting 'default'...
[11:41:32] Starting 'build'...
[11:41:32] Starting 'clean'...
[11:41:32] Finished 'clean' after 7.87 ms
[11:41:32] Starting 'pages'...
[11:41:32] Finished 'pages' after 357 ms
[11:41:32] Starting 'sass'...
[11:41:32] Finished 'sass' after 152 ms
[11:41:32] Starting 'images'...
[11:41:33] gulp-imagemin: Minified 0 images
[11:41:33] Finished 'images' after 283 ms
[11:41:33] Starting 'inline'...
[11:41:34] Finished 'inline' after 860 ms
[11:41:34] Finished 'build' after 1.66 s
[11:41:34] Starting 'server'...
[11:41:34] Finished 'server' after 44 ms
[11:41:34] Starting 'watch'...
[11:41:34] 'watch' errored after 27 ms
[11:41:34] Error: watch src/pages ENOSPC
    at exports._errnoException (util.js:896:11)
    at FSWatcher.start (fs.js:1423:19)
    at Object.fs.watch (fs.js:1450:11)
    at createFsWatchInstance (/var/www/html/emails/node_modules/gulp/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/var/www/html/emails/node_modules/gulp/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/var/www/html/emails/node_modules/gulp/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/var/www/html/emails/node_modules/gulp/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/var/www/html/emails/node_modules/gulp/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/var/www/html/emails/node_modules/gulp/node_modules/glob-watcher/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:117:15)
[11:41:34] 'default' errored after 1.74 s

npm ERR! Linux 4.4.9-300.fc23.x86_64
npm ERR! argv "/usr/local/bin/node" "/home/mendozah/.npm-packages/.npm-packages/bin/npm" "start"
npm ERR! node v6.0.0
npm ERR! npm  v3.9.0
npm ERR! code ELIFECYCLE
npm ERR! foundation-emails-template@1.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the foundation-emails-template@1.0.0 start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the foundation-emails-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs foundation-emails-template
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls foundation-emails-template
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/emails/npm-debug.log

If i try to run global gulp by just

`````` gulp```

it gives me the following error:
[11:42:26] Failed to load external module babel-register
[11:42:26] Requiring external module babel-core/register
[11:42:29] Using gulpfile /var/www/html/emails/gulpfile.babel.js
/home/mendozah/.npm-packages/.npm-packages/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /home/mendozah/.npm-packages/.npm-packages/lib/node_modules/gulp/bin/gulp.js:129:19
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:159:18)
    at node.js:444:3

Versions:
```npm start gulp --v
3.9.0```

```gulp --v
Local version 4.0.0-alpha.2
``````

both cli gives me 3.9.1.

Thanks!

**Comment by Hectorhammett** [comment]
No one?

**Comment by rafibomb** [comment]
npm installs could sometimes run into hiccups. It's been a thing with npm for a long time. Anytime we see an error, you can usually delete the node_modules folder and then run `npm install`

**Comment by Hectorhammett** [comment]
I already did that a few times, still nothing.

**Comment by rafibomb** [comment]
Hmm, what version of the CLI do you have? run `foundation -v`
<img width="309" alt="screen shot 2016-06-16 at 10 57 02 am" src="https://cloud.githubusercontent.com/assets/5652085/16127395/284d5db0-33b1-11e6-83b2-a241a77dc5b1.png">

**Comment by Hectorhammett** [comment]
(node:19238) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Foundation CLI version 2.1.0

**Comment by rafibomb** [comment]
I found this - http://stackoverflow.com/questions/35491905/npm-warn-deprecated-graceful-fs3-0-8-graceful-fs-version-3 Though I'm not sure what's causing your issue. Any one else have a suggestion?

**Comment by SebastianSchirmer** [comment]
It might be due to conflicting gulp versions. 

First, install gulp-cli globally (not just gulp) by running

```
npm install --global gulp-cli
```

If you have previously installed a version of gulp globally (which I assume you have), please run 
`npm rm --global gulp` first to make sure your old version doesn't collide with gulp-cli.

Then install gulp in your project devDependencies by running `npm install` in you project folder.

Everything above is basically copied from https://github.com/gulpjs/gulp/blob/master/docs/getting-started.md

This might help...

**Comment by tdhartwick** [comment]
Thanks @leschirmeur! @Hectorhammett, does this help?

**Comment by Andrew-Dyachenko** [comment]
This solution does not work. `gulp` command did not want to work. But I have found a solution with the help of the other comand `sudo npm start`

[info](https://foundation.zurb.com/emails/docs/sass-guide.html)

**Comment by rafibomb** [comment]
We'll close this is at doesn't appear to be a global issue, thanks!

**Comment by oskarOlausson** [comment]
It is, I have the problem aswell

**Comment by ralts00** [comment]
It is, I have the problem aswell

:(
