### ISSUE TITLE
[Getting Started with Sass] Failed to load external module babel-register

### ISSUE THREAD

**Issue by faithworksio** [foundation/foundation-emails#486]
**How can we reproduce this bug?**
Install resources as mentioned: http://foundation.zurb.com/emails/docs/sass-guide.html
Create project
Run the npm start script in that project directory: 

`$ npm start`

Looks like babel-register was was forgotten in package.json devDependancies?

**Comment by rafibomb** [comment]
We have an update for this that was tested on Foundation-sites. It will go out with 2.2!

**Comment by rafibomb** [comment]
@kball Are you able to apply the same fix from sites to the Emails Template?

**Comment by igorissen** [comment]
Same issue here.
- foundation: `2.1.0`
- node: `4.4.4`
- npm: `3.8.9`
- gulp:
  - CLI version: `3.9.1`
  - Local version: `4.0.0-alpha.2`

```
$ npm i babel-register
$ $(npm bin)/gulp
```

And I got this error from `node-sass`

```
[15:37:57] Requiring external module babel-register
[15:37:58] Using gulpfile ~/Projects/emails/most-anticipated/gulpfile.babel.js
[15:37:58] Starting 'default'...
[15:37:58] Starting 'build'...
[15:37:58] Starting 'clean'...
[15:37:58] Finished 'clean' after 5.6 ms
[15:37:58] Starting 'pages'...
[15:37:59] Finished 'pages' after 392 ms
[15:37:59] Starting 'sass'...
[15:37:59] 'sass' errored after 65 ms
[15:37:59] Error: ENOENT: no such file or directory, scandir '/Projects/emails/most-anticipated/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at Object.getInstalledBinaries (/Projects/emails/most-anticipated/node_modules/node-sass/lib/extensions.js:119:13)
    at foundBinariesList (/Projects/emails/most-anticipated/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Projects/emails/most-anticipated/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Projects/emails/most-anticipated/node_modules/node-sass/lib/errors.js:45:5)
    at Object.<anonymous> (/Projects/emails/most-anticipated/node_modules/node-sass/lib/index.js:15:28)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Projects/emails/most-anticipated/node_modules/babel-register/lib/node.js:166:7)
[15:37:59] 'build' errored after 467 ms
[15:37:59] 'default' errored after 469 ms
```

**Comment by yumyo** [comment]
+1

**Comment by DanielRuf** [comment]
This is not an actual error and can be ingored and closed.

**Comment by DanielRuf** [comment]
Closing as outdated and we did not receive any further feedback.

**Comment by ghost** [comment]
this is the error I'm getting when I run foundation watch:


[23:05:02] Requiring external module @babel/register
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/slickvick/Emails/node_modules/babel-preset-es2015/lib/index.js
