### ISSUE TITLE
Inliner crash on live rebuild

### ISSUE THREAD

**Issue by damongolding** [foundation/foundation-emails#599]
**How can we reproduce this bug?**
Saving upon making changes to a file

**What did you expect to happen?**
To build the files and reload browser

**What happened instead?**
Partial file build and no browser refresh

**Error code**

```
Unhandled rejection Error: empty style element
    at Object.<anonymous> (node_modules/gulp-inline-css/node_modules/inline-css/node_modules/extract-css/node_modules/style-data/index.js:30:22)
    at [object Object].exports.each (node_modules/gulp-inline-css/node_modules/inline-css/node_modules/cheerio/lib/api/traversing.js:293:24)
    at module.exports (node_modules/gulp-inline-css/node_modules/inline-css/node_modules/extract-css/node_modules/style-data/index.js:25:16)
    at node_modules/gulp-inline-css/node_modules/inline-css/node_modules/extract-css/index.js:14:9
    at next (node_modules/gulp-inline-css/node_modules/inline-css/node_modules/extract-css/node_modules/batch/index.js:118:7)
    at Batch.end (node_modules/gulp-inline-css/node_modules/inline-css/node_modules/extract-css/node_modules/batch/index.js:154:5)
    at module.exports (node_modules/gulp-inline-css/node_modules/inline-css/node_modules/extract-css/index.js:24:11)
    at node_modules/gulp-inline-css/node_modules/inline-css/lib/inlineContent.js:15:9
    at tryCatcher (node_modules/gulp-inline-css/node_modules/inline-css/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (node_modules/gulp-inline-css/node_modules/inline-css/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (node_modules/gulp-inline-css/node_modules/inline-css/node_modules/bluebird/js/main/promise.js:70:37)
    at inlineContent (node_modules/gulp-inline-css/node_modules/inline-css/lib/inlineContent.js:8:12)
    at node_modules/gulp-inline-css/node_modules/inline-css/index.js:27:9
    at tryCatcher (node_modules/gulp-inline-css/node_modules/inline-css/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (node_modules/gulp-inline-css/node_modules/inline-css/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (node_modules/gulp-inline-css/node_modules/inline-css/node_modules/bluebird/js/main/promise.js:70:37)
```

**Comment by cossssmin** [comment]
It says there you have an empty `style` element. Remove it and try again, I've never encountered this one before.

**Comment by damongolding** [comment]
I'm an absolute idiot. There was a copy of the old Ink framework hidden in my img folder....

I'll get my coat

**Comment by cossssmin** [comment]
No worries, small mistakes are hardest to spot. Don't forget to close this if it's resolved :)
