### ISSUE TITLE
Failed to load external module babel-register ...

### ISSUE THREAD

**Issue by SteffenGeorgi** [foundation/foundation-emails#717]
Local installation on iMac worked but if i try to install it on mac mini gave me that error:

username:template username$ npm start

foundation-emails-template@1.0.0 start /Volumes/Web/email/template
gulp

[11:13:46] Failed to load external module babel-register
[11:13:46] Failed to load external module babel-core/register
[11:13:46] Failed to load external module babel/register

/Volumes/Web/email/template/gulpfile.babel.js:1
(function (exports, require, module, __filename, __dirname) { import gulp     from 'gulp';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:198:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/flagged-respawn/index.js:17:3)

i tried:
- npm update
- npm install

Is there a problem when using it on an fileserver?

**Comment by SteffenGeorgi** [comment]
Ok it dont work with CLI but after cloning the repository and installation now it worked for me.
