### ISSUE TITLE
Error on 'gulp start' – ReferenceError: yargs is not defined 

### ISSUE THREAD

**Issue by jschnor** [foundation/foundation-emails#731]
I've uninstalled gulp, gulp-cli, deleted my node_modules folder, and researched everything I could find online and still can't seem to solve this one. I'm getting this error when running 'gulp start':

Starting 'server'...
[23:26:12] 'server' errored after 120 μs
[23:26:12] ReferenceError: yargs is not defined
    at Gulp.<anonymous> (/Users/jschnor/apps/flip2c-email/gulpfile.js:115:11)
    at module.exports (/Users/jschnor/apps/flip2c-email/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/jschnor/apps/flip2c-email/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/jschnor/apps/flip2c-email/node_modules/orchestrator/index.js:214:10)
    at /Users/jschnor/apps/flip2c-email/node_modules/orchestrator/index.js:279:18
    at finish (/Users/jschnor/apps/flip2c-email/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/jschnor/apps/flip2c-email/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/jschnor/apps/flip2c-email/node_modules/run-sequence/index.js:60:5)
    at runNextSet (/Users/jschnor/apps/flip2c-email/node_modules/run-sequence/index.js:88:5)
    at Gulp.onTaskEnd (/Users/jschnor/apps/flip2c-email/node_modules/run-sequence/index.js:75:5)

When I run: gulp -v
[23:29:42] CLI version 1.2.2
[23:29:42] Local version 3.9.1

I'm on MacOs Sierra 10.12.3
node v7.5.0
npm 4.1.2

I even ran 'npm install yargs' and I still get the error

**Comment by jschnor** [comment]
I resolved this myself. I actually had to 'npm install yargs' and require it in the gulpfile:

var yargs = require('yargs');

**Comment by meetwudi** [comment]
I don't know why you closed this but this is apprently a bug and should be fixed.

**Comment by meetwudi** [comment]
Oh I see, this is only in develop but not in master. I'd send a PR to develop soon.

**Comment by micada** [comment]
I just wanted to note that I ran into this issue as well and installed/required yargs to fix it. @tjwudi's PR would be super helpful.
