### ISSUE TITLE
New SASS project fails at installation step

### ISSUE THREAD

**Issue by 508LoopDetected** [foundation/foundation-emails#790]
I am setting up my first project. The Foundation CLI installs flawlessly with only a Bower deprecation warning. However, when I next run:

> foundation new --framework emails

Instead of prompting me to name a project, the command gives this error:

`/usr/local/lib/node_modules/foundation-cli/lib/commands/info.js:7
module.exports = function(args = {}) {
                               ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/foundation-cli/lib/index.js:4:9)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)`

Is this a bug with the latest version or something I can easily fix from my end?

**Comment by 508LoopDetected** [comment]
I've found this thread with 2 other people experiencing the same issue:
http://foundation.zurb.com/forum/posts/52764-foundation-sass-for-emails-install-failing

**Comment by cab00m** [comment]
I have the same issue. 

/usr/local/lib/node_modules/foundation-cli/lib/commands/info.js:7
module.exports = function(args = {}) {
                               ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/foundation-cli/lib/index.js:4:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

**Comment by browneye253** [comment]
Same here.  Anybody find a workaround?

**Comment by marekdlugos** [comment]
Same here.

**EDIT:** I have resolved this issue by upgrading my node, nvm and other components.

**Comment by RandalMc** [comment]
Same problem here.

C:\inetpub\wwwroot\sites>foundation new
C:\Users\Username\AppData\Roaming\npm\node_modules\foundation-cli\lib\commands\info.js:7
module.exports = function(args = {}) {
                               ^
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\Username\AppData\Roaming\npm\node_modules\foundation-cli\lib\index.js:4:9)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

**Comment by DanielRuf** [comment]
Which Node.js version do you use?

**Comment by DanielRuf** [comment]
Closing as we did not receivy any further feedback.
