### ISSUE TITLE
Npm start issue

### ISSUE THREAD

**Issue by sarath704** [foundation/foundation-emails#800]
$ npm start

> foundation-emails-template@1.0.0 start E:\Work\fly_dubai\gitlab\zurbemail\EmailProj
> gulp

[12:38:48] Failed to load external module babel-register
[12:38:48] Failed to load external module babel-core/register
[12:38:48] Failed to load external module babel/register
E:\Work\EmailProj\gitlab\zurbemail\flydubai\gulpfile.babel.js:1
(function (exports, require, module, __filename, __dirname) { import gulp     from 'gulp';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Liftoff.handleArguments (C:\Users\sarathn\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (C:\Users\sarathn\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:198:16)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\sarathn\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.3.1
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! foundation-emails-template@1.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the foundation-emails-template@1.0.0 start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the foundation-emails-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs foundation-emails-template
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls foundation-emails-template
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Work\EmailProj\gitlab\zurbemail\flydubai\npm-debug.log

**Comment by XAMelleOH** [comment]
Did you do `npm install` before running that ?

**Comment by sarath704** [comment]
yes, I cloned git hub project issue now resolved

**Comment by DanielRuf** [comment]
So we can close this?
