### ISSUE TITLE
Solution for 

### ISSUE THREAD

**Issue by garretthyder** [foundation/foundation-emails#822]
**How can we reproduce this bug?**

Error: Cannot find module 'nopt'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/garretthyder/Gitlab/indigenous-perspectives-society/newsletter/node_modules/gulp/node_modules/glob-watcher/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/node-pre-gyp.js:14:12)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)

Write out the HTML (or Inky code) that causes the issue.

**What did you expect to happen?**

**What happened instead?**

**What email clients does this happen in?**

**Comment by garretthyder** [comment]
Oops, looks like this is a partial of the actual ticket I made;
https://github.com/zurb/foundation-emails/issues/823

Srry for any confusion.
