### ISSUE TITLE
Solution for "Error: cannot find module 'nopt'" on install

### ISSUE THREAD

**Issue by garretthyder** [foundation/foundation-emails#823]
Running `foundation new --framework emails` on an outdated environment I kept hitting the following error;
```
Error: Cannot find module 'nopt'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/garretthyder/Gitlab/indigenous-perspectives-society/newsletter/node_modules/gulp/node_modules/glob-watcher/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/node-pre-gyp.js:14:12)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```

The first time I ran into this updating node worked, I used these instructions;
http://blog.teamtreehouse.com/install-node-js-npm-mac

On another machine I ran into this the node update didn't resolve and had to install node-pre-gyp globally;
npm install -g node-pre-gyp

*Posting to help others, closing immediately as no action needed.

**Comment by Amm1rr** [comment]
In my case, I wasn't able to run npm because of the **nopt library**. To resolve the issue, I manually created the following directory structure and content at the specified path in Linux:

    /usr/lib/node_modules/npm/node_modules/nopt/

You can find the **nopt** library at this link: **[nopt library][1]**

After doing this, the problem was resolved, and now npm is working as expected.

__Note:__ Posting to help others.

  [1]: https://www.npmjs.com/package/nopt?activeTab=code

**Comment by Linux-NDOB** [comment]
Hi, i'm using Manjaro Linux at the latest update of this month, i got this error too although i uninstalled, cleaned and reinstalled npm before updated my system. So was using nvm(node version manager) and setting as desired version Node v18.18.0, for solve my problem i just downloaded and set as main version the current LTS Node v18.18.2 and the error got dissipated, any other method i tried didn't worked for me, just said it if someone got this error, the answer above didn't worked for me too :c. Good luck! :3

**Comment by mistekko** [comment]
Worked for me on Arch.
