### ISSUE TITLE
AWS not working when sending test to litmus.

### ISSUE THREAD

**Issue by Matt-Owens** [foundation/foundation-emails#828]
Whenever I add an image to an email, and push to litmus, I get the following error on the AWS task:

[15:39:38] 'aws' errored after 1.63 s
[15:39:38] 503: null
    at Request.extractError (/Users/mattowens/Desktop/SCT/node_modules/gulp-awspublish/node_modules/aws-sdk/lib/services/s3.js:577:35)
    at Request.callListeners (/Users/mattowens/Desktop/SCT/node_modules/gulp-awspublish/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/mattowens/Desktop/SCT/node_modules/gulp-awspublish/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/mattowens/Desktop/SCT/node_modules/gulp-awspublish/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/mattowens/Desktop/SCT/node_modules/gulp-awspublish/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/mattowens/Desktop/SCT/node_modules/gulp-awspublish/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/mattowens/Desktop/SCT/node_modules/gulp-awspublish/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/mattowens/Desktop/SCT/node_modules/gulp-awspublish/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/mattowens/Desktop/SCT/node_modules/gulp-awspublish/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/mattowens/Desktop/SCT/node_modules/gulp-awspublish/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/mattowens/Desktop/SCT/node_modules/gulp-awspublish/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/mattowens/Desktop/SCT/node_modules/gulp-awspublish/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/mattowens/Desktop/SCT/node_modules/gulp-awspublish/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/mattowens/Desktop/SCT/node_modules/gulp-awspublish/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/mattowens/Desktop/SCT/node_modules/gulp-awspublish/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/mattowens/Desktop/SCT/node_modules/gulp-awspublish/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/mattowens/Desktop/SCT/node_modules/gulp-awspublish/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/mattowens/Desktop/SCT/node_modules/gulp-awspublish/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (/Users/mattowens/Desktop/SCT/node_modules/gulp-awspublish/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at IncomingMessage.onEnd (/Users/mattowens/Desktop/SCT/node_modules/gulp-awspublish/node_modules/aws-sdk/lib/event_listeners.js:269:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)

I have gone back to all my previously developed emails that worked fine, and am now getting the same error.

Anyone else experiencing this?

**Comment by Matt-Owens** [comment]
And all of a sudden it looks like it is working again.  Must have been the AWS outage.
