### ISSUE TITLE
Failed to load external module @babel/register

### ISSUE THREAD

**Issue by lipis** [foundation/foundation-emails#868]
Is there anything I can do to avoid this error/warning?!

```bash
$ yarn build
yarn run v1.3.2
$ gulp build --production
[12:01:58] Failed to load external module @babel/register
[12:01:58] Requiring external module babel-register
```

**Comment by nikitasol** [comment]
Hello @lipis,

This issue has been widely discussed on gulp's repository. Basically it doesn't do any harm. It just tries to execute one thing and when it doesn't find it it executes the correct and intended module. It doesn't affect the production. It has been around since a long time.

**Comment by DanielRuf** [comment]
You can ignore it, it is basically just a warning.

**Comment by OrionPro** [comment]
Failed to load external module @babel/register
 Requiring external module babel-register
project\email-template\gulpfile.babel.js:71
_gulp2.default.task('build', _gulp2.default.series(clean, pages, sass, images, inline));
                                            ^

TypeError: _gulp2.default.series is not a function
 Not work ...
![image](https://user-images.githubusercontent.com/16542711/37706507-6aecdbb2-2d08-11e8-8d4c-8bb01955865a.png)
node v8.10.0
gulp tried and gulp@3.9.1 and 4+ ver ...
ps devDependencies all updated maximum
installed via npm install --global foundation-cli
foundation new --framework emails

**Comment by OrionPro** [comment]
Eventually, I solved the problem. I use git clone https://github.com/zurb/foundation-emails-template project, cd project, npm install, then I up node-sass  to version 3.1.0 (without it did not work) and it all worked. But the option with foundation new --framework emails not work for me (

**Comment by DanielRuf** [comment]
Not sure what you mean. A fresh install (on macOS) does not produce any error on my side (Node 8 and npm 5).

It is just a warning, not a bug or error.
The other dependencies should be installed by default.

**Comment by DanielRuf** [comment]
Is this a Windows machine and did you get other errors during the first install eg with node-sass and other parts? Then you need the `windows-build-tools` for node-gyp.

**Comment by DanielRuf** [comment]
```sh
gulp --version
[13:53:11] CLI version 3.9.1
```

Did you install gulp globally (the CLI)?

**Comment by OrionPro** [comment]
Yes of course I installed.  (gulp globally and CLI)  I have a lot of other projects and they work fine.

**Comment by OrionPro** [comment]
@DanielRuf I tried it many times, but nothing happened (npm install --global foundation-cli). Through git clone https://github.com/zurb/foundation-emails-template everything worked, only node-sass has updated

**Comment by DanielRuf** [comment]
In most cases you have to rebuild `node-sass` when it is updated.

**Comment by hey-yo** [comment]
@OrionPro may be **npm i "github:gulpjs/gulp#4.0"**. For me it work.

**Comment by DanielRuf** [comment]
Closing as we did not receive any further feedback.

**Comment by ghost** [comment]
I get this when I run foundation watch

Requiring external module babel-register
ReferenceError: globalThis is not defined
    at Object.<anonymous> (/Users/slickvick/Emails/node_modules/sass/sass.dart.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/slickvick/Emails/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/slickvick/Emails/node_modules/sass/sass.node.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
Error: foundation-emails-template@2.4.0 start: `gulp`
Exit status 1
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/foundation-cli/node_modules/npm/lib/utils/lifecycle.js:217:16)
    at EventEmitter.emit (events.js:193:13)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/foundation-cli/node_modules/npm/lib/utils/spawn.js:24:14)
    at ChildProcess.emit (events.js:193:13)
    at maybeClose (internal/child_process.js:999:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
