### ISSUE TITLE
Starting 'inline'... Unhandled rejection TypeError: __html.replace is not a function

### ISSUE THREAD

**Issue by vitaliykyrylyuk** [foundation/foundation-emails#880]
New foundation installation.

` master@master  /var/www/foundation-git/project   master  npm run build

> foundation-emails-template@1.0.0 build /var/www/foundation-git/project
> gulp --production

[15:00:49] Failed to load external module @babel/register
[15:00:49] Requiring external module babel-register
[15:00:50] Using gulpfile /var/www/foundation-git/project/gulpfile.babel.js
[15:00:50] Starting 'default'...
[15:00:50] Starting 'build'...
[15:00:50] Starting 'clean'...
[15:00:50] Finished 'clean' after 35 ms
[15:00:50] Starting 'pages'...
[15:00:50] Finished 'pages' after 469 ms
[15:00:50] Starting 'sass'...
[15:00:51] Finished 'sass' after 767 ms
[15:00:51] Starting 'images'...
[15:00:51] gulp-imagemin: Minified 0 images
[15:00:51] Finished 'images' after 56 ms
[15:00:51] Starting 'inline'...
Unhandled rejection TypeError: __html.replace is not a function
    at /var/www/foundation-git/project/node_modules/list-stylesheets/index.js:27:33
    at Array.forEach (<anonymous>)
    at encodeCodeBlocks (/var/www/foundation-git/project/node_modules/list-stylesheets/index.js:24:33)
    at encodeEntities (/var/www/foundation-git/project/node_modules/list-stylesheets/index.js:45:20)
    at module.exports (/var/www/foundation-git/project/node_modules/list-stylesheets/index.js:52:22)
    at module.exports (/var/www/foundation-git/project/node_modules/extract-css/index.js:11:16)
    at /var/www/foundation-git/project/node_modules/inline-css/lib/inlineContent.js:15:9
    at Promise._execute (/var/www/foundation-git/project/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/var/www/foundation-git/project/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/var/www/foundation-git/project/node_modules/bluebird/js/release/promise.js:79:10)
    at inlineContent (/var/www/foundation-git/project/node_modules/inline-css/lib/inlineContent.js:8:12)
    at /var/www/foundation-git/project/node_modules/inline-css/index.js:31:9
    at Promise._execute (/var/www/foundation-git/project/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/var/www/foundation-git/project/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/var/www/foundation-git/project/node_modules/bluebird/js/release/promise.js:79:10)
    at module.exports (/var/www/foundation-git/project/node_modules/inline-css/index.js:8:12)
    at DestroyableTransform._transform (/var/www/foundation-git/project/node_modules/gulp-inline-css/index.js:28:9)
    at DestroyableTransform.Transform._read (/var/www/foundation-git/project/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/var/www/foundation-git/project/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/var/www/foundation-git/project/node_modules/readable-stream/lib/_stream_writable.js:418:64)
    at writeOrBuffer (/var/www/foundation-git/project/node_modules/readable-stream/lib/_stream_writable.js:407:5)
    at DestroyableTransform.Writable.write (/var/www/foundation-git/project/node_modules/readable-stream/lib/_stream_writable.js:334:11)

[15:00:51] The following tasks did not complete: default, build, inline
[15:00:51] Did you forget to signal async completion?

master@master  /var/www/foundation-git/project   master  node -v  
v9.7.1
 master@master  /var/www/foundation-git/project   master  npm -v       
5.7.1`

But `npm start` task works, seems something wrong with inline gulp task

**Comment by dmsps** [comment]
Yeah, the same problem.

This is the new version of gulp-inline-css, waiting for fix.

Owner comment here
https://github.com/jonkemp/gulp-inline-css/issues/50#issuecomment-370794823

**Comment by jonaslimads** [comment]
The problem seems to be on the list-stylesheets plugins. I went to node_modules/list-stylesheets/index.js and put a try-catch block around __html.replace, so

```javascript
                try {
                    __html = __html.replace(re, function (match) {
                        codeBlockLookup.push(match);
                        return 'EXCS_CODE_BLOCK_' + (codeBlockLookup.length - 1) + '_';
                    });
                } catch(e) {}
```

I'm not sure if this makes any difference on the output, but it supressed the error and at least now I have an inline HTML.

**Comment by jonkemp** [comment]
Fix is available.

https://github.com/jonkemp/gulp-inline-css/releases/tag/v3.1.3

**Comment by DanielRuf** [comment]
So we can close this then?

**Comment by jonkemp** [comment]
I would think so. Updating to the latest version of the plugin fixes the issue.

**Comment by jonkemp** [comment]
I would recommend adding a lockfile though, which would have prevented this from happening. The lockfile can be generated with yarn or npm 5. I'll create a separate issue for this.

**Comment by DanielRuf** [comment]
This would not prevent this.

**Comment by jonkemp** [comment]
I'm not sure about that. Or my understanding of lockfiles is flawed.

https://docs.npmjs.com/files/package-locks

> It is highly recommended you commit the generated package lock to source control: this will allow anyone else on your team, your deployments, your CI/continuous integration, and anyone else who runs npm install in your package source to get the exact same dependency tree that you were developing on. Additionally, the diffs from these changes are human-readable and will inform you of any changes npm has made to your node_modules, so you can notice if any transitive dependencies were updated, hoisted, etc.

**Comment by DanielRuf** [comment]
In general if you run `npm i foundation-emails`, they do not lock anything.

**Comment by jonkemp** [comment]
Ah, I see what you mean.

**Comment by DanielRuf** [comment]
Closing as we did not receivy any further feedback.
