### ISSUE TITLE
Foundation Emails Version Sass Install and Running the Server with Yarn

### ISSUE THREAD

**Issue by funcion** [foundation/foundation-emails#888]
I am trying to run the server with the command **yarn run** and it shows me the following message.

**Note:** I have followed all the steps specified here https://foundation.zurb.com/emails/docs/sass-guide.html the reason why I have not done it with **npm**, it is because it is taking too long to install the dependencies, I have left installing from yesterday and spent more than 12 hours and had not installed all these, this is partly by the Internet connection but likewise takes a long time, however with **yarn** was very fast in seconds.

```
C:\xampp\htdocs\yarn\foundation-emails>yarn run
yarn run v1.5.1
error No command specified.
info Commands available from binary scripts: acorn, acorn.cmd, atob, atob.cmd, babylon, babylon.cmd, browser-sync, browser-sync.cmd, cleancss, cleancs
s.cmd, color-support, color-support.cmd, css-beautify, css-beautify.cmd, csso, csso.cmd, dev-ip, dev-ip.cmd, editorconfig, editorconfig.cmd, escodegen
, escodegen.cmd, esgenerate, esgenerate.cmd, eslint, eslint.cmd, esparse, esparse.cmd, esvalidate, esvalidate.cmd, glob-all, glob-all.cmd, gonzales, g
onzales.cmd, gulp, gulp.cmd, handlebars, handlebars.cmd, he, he.cmd, html-beautify, html-beautify.cmd, html-minifier, html-minifier.cmd, in-install, i
n-install.cmd, in-publish, in-publish.cmd, is-ci, is-ci.cmd, js-beautify, js-beautify.cmd, js-yaml, js-yaml.cmd, jsdoc, jsdoc.cmd, lt, lt.cmd, marked,
 marked.cmd, md2html, md2html.cmd, mime, mime.cmd, mkdirp, mkdirp.cmd, node-gyp, node-gyp.cmd, node-sass, node-sass.cmd, nopt, nopt.cmd, not-in-instal
l, not-in-install.cmd, not-in-publish, not-in-publish.cmd, panini, panini.cmd, rc, rc.cmd, rimraf, rimraf.cmd, sass-lint, sass-lint.cmd, sassdoc, sass
doc.cmd, sassgraph, sassgraph.cmd, semver, semver.cmd, shjs, shjs.cmd, sshpk-conv, sshpk-conv.cmd, sshpk-sign, sshpk-sign.cmd, sshpk-verify, sshpk-ver
ify.cmd, strip-bom, strip-bom.cmd, strip-json-comments, strip-json-comments.cmd, supercollider, supercollider.cmd, svgo, svgo.cmd, swig, swig.cmd, thr
ottleproxy, throttleproxy.cmd, uglifyjs, uglifyjs.cmd, uuid, uuid.cmd, which, which.cmd, window-size, window-size.cmd
info Project commands
   - deploy:dist
      gulp dist
   - deploy:docs
      gulp deploy:docs
   - deploy:download
      gulp download
   - deploy:settings
      gulp settings
   - deploy:templates
      gulp templates
   - start
      gulp
   - test:visual
      gulp test
question Which command would you like to run?:
```

**Note:** I will explain all the steps I did from cloning the repository and installing dependencies.

**Step 1: Clone the project with GIT - All good without problems**

`git clone https://github.com/zurb/foundation-emails.git`

**Step 2: Install all dependencies - All good without problems**

`yarn install`

**Step 3: I'm trying to run the server - It shows me the following message**

`yarn start`

```
C:\xampp\htdocs\yarn\foundation-emails>yarn start
yarn run v1.5.1
$ gulp
[13:58:48] Using gulpfile C:\xampp\htdocs\yarn\foundation-emails\gulpfile.js
[13:58:48] Starting 'build'...
[13:58:48] Starting 'clean'...
[13:58:48] Finished 'clean' after 52 ms
[13:58:48] Starting 'copy'...
[13:58:48] Starting 'copy-inky'...
[13:58:48] Starting 'html'...
[13:58:48] Starting 'sass:docs'...
[13:58:48] 'sass:docs' errored after 49 ms
[13:58:48] Error: Node Sass does not yet support your current environment: Windows 32-bit with Unsupported runtime (57)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1
    at module.exports (C:\xampp\htdocs\yarn\foundation-emails\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (C:\xampp\htdocs\yarn\foundation-emails\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\xampp\htdocs\yarn\foundation-emails\node_modules\gulp-sass\index.js:187:21)
[13:58:48] 'build' errored after 421 ms
[13:58:48] Error in plugin 'run-sequence(sass:docs)'
Message:
    Node Sass does not yet support your current environment: Windows 32-bit with Unsupported runtime (57)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1
Stack:
Error: Node Sass does not yet support your current environment: Windows 32-bit with Unsupported runtime (57)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1
    at module.exports (C:\xampp\htdocs\yarn\foundation-emails\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (C:\xampp\htdocs\yarn\foundation-emails\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\xampp\htdocs\yarn\foundation-emails\node_modules\gulp-sass\index.js:187:21)
[13:58:49] Supercollider: processed alignment.html in 0.57 s
[13:58:50] Finished 'copy-inky' after 1.62 s
[13:58:50] Supercollider: processed button.html in 1.00 s with sass
[13:58:50] Supercollider: processed callout.html in 0.85 s with sass
[13:58:50] Supercollider: processed compatibility.html in 0.93 s
[13:58:50] Supercollider: processed css-guide.html in 0.93 s
[13:58:50] Supercollider: processed gem-guide.html in 0.95 s
[13:58:50] Supercollider: processed global.html in 0.97 s with sass
[13:58:50] Supercollider: processed grid.html in 0.01 s with sass
[13:58:50] Supercollider: processed index.html in 0.08 s
[13:58:50] Supercollider: processed inky.html in 0.09 s
[13:58:50] Supercollider: processed media-query.html in 0.11 s
[13:58:50] Supercollider: processed menu.html in 0.13 s with sass
[13:58:50] Supercollider: processed migration.html in 0.18 s
[13:58:50] Supercollider: processed panini.html in 0.21 s
[13:58:50] Supercollider: processed sass-guide.html in 0.23 s
[13:58:50] Supercollider: processed sass.html in 0.24 s
[13:58:50] Supercollider: processed spacer.html in 0.26 s
[13:58:50] Supercollider: processed styling.html in 0.28 s
[13:58:50] Supercollider: processed thumbnail.html in 0.28 s
[13:58:50] Supercollider: processed tips-tricks.html in 0.29 s
[13:58:50] Supercollider: processed typography.html in 0.31 s with sass
[13:58:50] Supercollider: processed visibility.html in 0.35 s
[13:58:50] Supercollider: processed wrapper.html in 0.37 s
[13:58:50] Supercollider: processed zurb-stack.html in 0.41 s
[13:58:50] Finished 'copy' after 2.32 s
[13:58:50] Finished 'html' after 2.32 s
error An unexpected error occurred: "Command failed.
```

**Comment by DanielRuf** [comment]
Try upgrading gulp-sass and node-sass.

**Comment by DanielRuf** [comment]
Closing as we did not receive any further feedback.
