### ISSUE TITLE
Cannot find module './$data'

### ISSUE THREAD

**Issue by bhaveshpatil075** [foundation/foundation-emails#894]
Error: Cannot find module './$data'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Bhavesh\Project\SurveyTool\SurveyTool.App\SurveyTo
ol.Web\node_modules\@angular-devkit\core\node_modules\ajv\lib\ajv.js:10:23)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by DanielRuf** [comment]
Hi @bhaveshpatil075,

We can not reproduce this. Please provide the steps that you have done to get this result.

It seems this is related to `@angular-devkit` which is not used in foundation-emails.
