### ISSUE TITLE
[Getting Started with Sass] Can't start new email project

### ISSUE THREAD

**Issue by Chillifish** [foundation/foundation-emails#954]
**How can we reproduce this bug?**
`foundation new --framework emails`

Write out the HTML (or Inky code) that causes the issue.

**What did you expect to happen?**
To be asked for a project name

**What happened instead?**

`ReferenceError: primordials is not defined
    at fs.js:27:35
    at req_ (/usr/local/lib/node_modules/foundation-cli/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/usr/local/lib/node_modules/foundation-cli/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/foundation-cli/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)`

**What email clients does this happen in?**
N/A

**Comment by Chillifish** [comment]
I hadn't noticed that this project no longer seems to be live.

**Comment by jwogrady** [comment]
@Chillifish confirming.... same issue.  Using OSX.  Installed node with brew.

results of install....

```
$ sudo npm install --global foundation-cli
npm WARN deprecated bower@1.8.8: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
/usr/local/bin/foundation -> /usr/local/lib/node_modules/foundation-cli/bin/foundation.js
```

Results of foundation command....

```
ReferenceError: primordials is not defined
    at fs.js:27:35
    at req_ (/usr/local/lib/node_modules/foundation-cli/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/usr/local/lib/node_modules/foundation-cli/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/foundation-cli/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
```

**Comment by cmattson** [comment]
Released versions of Foundation have some older dependencies which unfortunately do not like Node versions newer than 10.

If you're on macOS and using Homebrew, you can install Node 10 alongside your newer Node installation with `brew install node@10`. Note that you will need to add the Node 10 binaries to the beginning of your PATH when you want to work with Node 10 (see the details Homebrew provides).

If you're on another OS, it may provide avenues for parallel installs as well. In any case, you can always fire up a Vagrant/Docker/regular VM pinned to Node 10.

You might also try re-reporting this at [zurb/foundation-sites](https://github.com/zurb/foundation-sites), which is where the `foundation` tool is developed.

**Comment by joshmobley** [comment]
Issues on Node v8.11.4 as well -- cannot successfully install dependencies from npm.

```npm WARN deprecated cryptiles@0.2.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@0.2.4: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated mimelib@0.2.19: This project is unmaintained
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm ERR! code 1
npm ERR! Command failed: git checkout 4.0
npm ERR! error: pathspec '4.0' did not match any file(s) known to git.
```

**Comment by Jonesdl-2785** [comment]
Same issue with Node 12.1.0 using Ubuntu.
node: v12.1.0
npm: 6.9.0
gulp CLI version: 2.2.0
gulp Local version: 4.0.2

fs.js:27
const { Math, Object, Reflect } = primordials;
                                  ^

ReferenceError: primordials is not defined
    at fs.js:27:35
    at req_ (.../node_modules/natives/index.js:143:24)
    at Object.req [as require] (.../node_modules/natives/index.js:55:10)
    at Object.<anonymous> (.../node_modules/gulp-require-tasks/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Module._compile (.../node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Object.newLoader [as .js] (.../node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)

Here is the response I received from the gulp github issues support:
'We don't ship the graceful-fs that includes the natives module with gulp 4 - that version of graceful-fs is extremely old and you shouldn't be using it.'

Please advise how to get around this issue.

**Comment by DanielRuf** [comment]
Please use NodeJS 10 using nvm or alternatives.

See https://github.com/zurb/foundation-sites/issues/11755

**Comment by DanielRuf** [comment]
> You might also try re-reporting this at [zurb/foundation-sites](https://github.com/zurb/foundation-sites), which is where the `foundation` tool is developed.

You mean https://github.com/zurb/foundation-cli

**Comment by DanielRuf** [comment]
> npm ERR! error: pathspec '4.0' did not match any file(s) known to git.

Please change the `gulp` entry in package.json to use 4.0.0. The gulp maintainers deleted the `4.0` tag which causes this.

**Comment by DanielRuf** [comment]
Please keep in min that creating multiple issues about the exact same problem is not helpful for us maintainers.

**Comment by DanielRuf** [comment]
Please keep in mind that creating multiple issues about the exact same problem is not helpful for us maintainers.
