### ISSUE TITLE
Foundation for emails has stopped working

### ISSUE THREAD

**Issue by Cozmonaut** [foundation/foundation-emails#964]
**How can we reproduce this bug?**
Hi, 

My foundation for emails has been working fine and today when I opened up terminal and tried to run npm start, no dice. 

I'm not overly technical so all I've done is plugged my error into google and tried all the things people have suggested in various threads where the same issue has occurred. Nothing is working. I also tried running a fresh install in case there was something broken in my code but that's not working either. 

Here is my error log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.11.3
3 info using node@v10.16.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle foundation-emails-template@1.0.0~prestart: foundation-emails-template@1.0.0
6 info lifecycle foundation-emails-template@1.0.0~start: foundation-emails-template@1.0.0
7 verbose lifecycle foundation-emails-template@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle foundation-emails-template@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/corinne/Sites/hws/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle foundation-emails-template@1.0.0~start: CWD: /Users/corinne/Sites/hws
10 silly lifecycle foundation-emails-template@1.0.0~start: Args: [ '-c', 'gulp' ]
11 info lifecycle foundation-emails-template@1.0.0~start: Failed to exec start script
12 verbose stack Error: foundation-emails-template@1.0.0 start: `gulp`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:198:13)
12 verbose stack     at maybeClose (internal/child_process.js:982:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
13 verbose pkgid foundation-emails-template@1.0.0
14 verbose cwd /Users/corinne/Sites/hws
15 verbose Darwin 18.7.0
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
17 verbose node v10.16.0
18 verbose npm  v6.11.3
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error foundation-emails-template@1.0.0 start: `gulp`
23 error spawn ENOENT
24 error Failed at the foundation-emails-template@1.0.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
~                           

**What did you expect to happen?**
I expected a tab to open with my local host url showing the usual Foundation for emails page. 

**What happened instead?**
npm start error as per the log pasted above. 

**What email clients does this happen in?**
NA

I would be so grateful if you can help me troubleshoot this as I need to build out some more email templates and much prefer using Foundation for Emails templating framework.

**Comment by diomededavid** [comment]
This is not idea, but download a new copy and replace the `package.json` file from the new copy to your folder. Delete your node modules folder and do a `npm install` from your projects folder. That should bring you back up.

**Comment by DanielRuf** [comment]
Hi @Cozmonaut,

please check if you can still run `gulp` on your terminal / shell.

**Comment by adigitalnative** [comment]
This may be dead, but I notice from your logs that you are running Node version 10.16.x. I haven't tried to run it on 10.x, but I know that when I run it in 8.x and 11.x I get errors.

If you are using some kind of version manager for Node, i.e. NVM, try earlier versions of Node to see if that solves your problem.

**Comment by DanielRuf** [comment]
This is not a problem with node.

**Comment by Cozmonaut** [comment]
Hi @adigitalnative, I've tried it on the latest version of node, older versions and then read somewhere I should be using 10. @DanielRuf I checked gulp way back when you mentioned it and something odd was going on. So I tried removing everything and starting again but for some reason, the SCSS wouldn't compile anymore. I need to build an email today so I'll give it one quick crack and see how I go.

**Comment by DanielRuf** [comment]
What did you get when you tried `gulp` in the project folder? And also `./node_modules/.bin/gulp`?

**Comment by rickydazla** [comment]
I ran into similar issues and solved by switching to Node v7.x, deleting node_modules folder and then running npm install. This project should really be updated as on install a bunch of warning are thrown as there are many dependencies that are no longer maintained, deprecated, etc. etc.

**Comment by DanielRuf** [comment]
> warning are thrown as there are many dependencies that are no longer maintained, deprecated, etc. etc.

Warnings are not problematic.

Does Node v8 not work for you?

**Comment by rickydazla** [comment]
@DanielRuf sure, it does. But when you install a project that outputs the following, it's usually an indication that an update is due: `found 630 vulnerabilities (63 low, 128 moderate, 438 high, 1 critical)`. Don't get me wrong, I love this framework and appreciate the hard work you and others have put into it. I fully understand the reasons for its current state and correct me if I'm wrong, but to me this is an indication that it might be getting a little long in the tooth.

**Comment by DanielRuf** [comment]
We are aware of that and will update everything in the upcoming months.

But this does not mean that it does not work as the title suggests.

**Comment by rickydazla** [comment]
I didn’t create this issue, in fact I provided the OP with a solution in the same response you quoted :)

**Comment by DanielRuf** [comment]
In general only even Node release numbers should be used (6, 8, 10, 12) as these are LTS releases and live longer than the odd ones. Node 7 reached EOL earlier than Node 6 (affects security).

You may only need `npm ci`.

**Comment by joeworkman** [comment]
Foundation for Emails has been superseded by [Inky v2](https://github.com/foundation/inky), a complete rewrite in Rust with improved Outlook support, hybrid output mode, bulletproof buttons, validation, and more. This issue will not be addressed in the legacy codebase.

If this issue persists in v2, please open a new issue at https://github.com/foundation/inky/issues
